### ISSUE TITLE
MKS SKIPR goes not in DFU Mode after canboot

### ISSUE THREAD

**Issue by yammaster** [Arksine/katapult#107]
The SKIPR board uses for klipper configuration normaly Bootloader offset (48KiB bootloader (MKS Robin Nano V3)). So in my mind I should in CanBoot configure the Application start offset to 48KiB - or is this wrong? Doesn't matter what's configured, the canboot with

`~/CanBoot$ python3 ~/CanBoot/scripts/flash_can.py -u e97aff00bbc7` 

fails with 

`ERROR:root:Flash Error
Traceback (most recent call last):
  File "/home/mks/CanBoot/scripts/flash_can.py", line 458, in run
    self.cansock.bind((intf,))
OSError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mks/CanBoot/scripts/flash_can.py", line 622, in main
    loop.run_until_complete(sock.run(intf, uuid, fpath, req_only))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mks/CanBoot/scripts/flash_can.py", line 460, in run
    raise FlashCanError("Unable to bind socket to can0")
FlashCanError: Unable to bind socket to can0`
 
maybe this error will disappear with the right offset settings - need help, please.

**Comment by datarius2** [comment]
install:
`pip3 install pyserial`
